DROP TABLE IF EXISTS supplier;

CREATE TABLE supplier(
SLNO TEXT,
SNAME TEXT,
STATUS INTEGER,
CITY TEXT);

INSERT INTO supplier(SLNO, SNAME, STATUS, CITY)VALUES
('S1','AARUSH',2,'BATALA'),
('S2','KARAN',3,'BATALA'),
('S3','KUNWAR',4,'BATALA'),
('S4','SHIVANSH',5,'AMRITSAR');

SELECT * FROM supplier;

SELECT * 
FROM supplier
WHERE CITY='AMRITSAR';